Added New Map, NEED TO FIX MEMORY LEAKS
After around 5-6 exfils, memory starts leaking these causing you to not be able to play certain maps

  ERROR: 254 RID allocations of type '8NavAgent' were leaked at exit.

  ERROR: 120 RID allocations of type '9NavRegion' were leaked at exit.

  ERROR: 367 RID allocations of type 'P11GodotBody3D' were leaked at exit.

  ERROR: 157 RID allocations of type 'P11GodotArea3D' were leaked at exit.

  ERROR: 10 RID allocations of type 'P12GodotShape3D' were leaked at exit.